# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winterblog', '0004_auto_20180107_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winterblog.Blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='winterblog.Blogger'),
        ),
    ]
